def activity3():
    name = input("Enter your full name: ")
    age = input("Enter your age: ")
    gender = input("Enter your gender: ")
    bday = input("Enter your bithday: ")       
    birthplace = input("Enter your birthplace: ")
    height = float(input("Enter your height in cm: "))
    weight = float(input("Enter your weight in kg: "))
    fathers_name = input("Enter your fathers name: ")
    mothers_name = input("Enter your mothers name: ")
    address = input("Enter your address: ")
    civil_status = input("What is your civil status? ")
    relilgion = input("Enter your religion: ")
    phone_number = input("Enter your phone number: ")
    email = input("Enter your email: ")

    print("My name is ", name , "a", age , "year/s old", gender, "born on ", bday , "in " + birthplace + ". I am " + height + " cm tall and weigh ", weight , "kg. ")
